### ISSUE TITLE
className移除后某些css属性没有相应的移除

### ISSUE THREAD

**Issue by 25juan** [didi/Hummer#265]
## 描述
className移除后某些css属性没有相应的移除

## Hummer version:
@hummer/cli@0.1.27

## 复现步骤
1. 参考下面demo

## 预期结果
1 希望透明度为1

## 样例代码、屏幕截图或者仓库链接
```css
.text {
  padding: 32px;
  font-size: 50px;
  opacity: 1;
}
.text-md {
  opacity: 0;
}

```
```jsx
import React, { useState } from 'react';
import classNames from "classnames";

export default () => {
  const [md, setMD] = useState(false);
  const viewClassName = classNames("text",{
    'text-md': md
  });
  return (
    <text onTap={() => setMD(!md)} className={viewClassName}>hello word</text>
  )
};

```
