### ISSUE TITLE
标签css属性 background-image 无效

### ISSUE THREAD

**Issue by BenXueYou** [didi/Hummer#410]
https://hummer.didi.cn/doc-tenon#/zh-CN/basic_style
## 描述
基础样式中

background-image: url("https://dpubstatic.udache.com/static/dpubimg/RJ4ZZ_M5ie/WechatIMG24764.jpeg");

## Hummer version:

@hummer/cli@0.10.3
 @hummer/tenon-vue": "^1.7.0",
## 复现步骤

1.  下载github官方仓库代码
2.  进入路径 cd .\examples\tenon-vue\
3.  安装依赖 npm install
4.  启动命令 npm run dev
5.  打开项目playground 终端
6.  进入component-view.js页面
7.  展示的图片为：

## 预期结果

展示背景图片

![image123](https://user-images.githubusercontent.com/20661903/192275710-749e6453-a9b9-44f8-9d10-6942c607eb84.png)

## 样例代码、屏幕截图或者仓库链接

```html
<view class="item-container">
     <view class="demo-box background-box"></view>
</view>
```

```css
.background-box {
  background-image: url("https://dpubstatic.udache.com/static/dpubimg/RJ4ZZ_M5ie/WechatIMG24764.jpeg");
}
```
